### ISSUE TITLE
Dependencies?

### ISSUE THREAD

**Issue by dxoigmn** [poloclub/jpeg-defense#1]
I'm trying to get orchestrator.py running and I'm running into import errors:

```
$ python orchestrator.py
Traceback (most recent call last):
  File "orchestrator.py", line 6, in <module>
    from attack import attack_and_save_images
  File "/home/ccorneli/Projects/jpeg-defense/attack.py", line 7, in <module>
    from params import *
  File "/home/ccorneli/Projects/jpeg-defense/params.py", line 5, in <module>
    from models.inception_v4 import InceptionV4
  File "/home/ccorneli/Projects/jpeg-defense/models/inception_v4.py", line 7, in <module>
    from heimdall.model import BaseModel as HeimdallModel
ModuleNotFoundError: No module named 'heimdall'
```

I don't think this is apart of cleverhans nor tf-slim, or am I mistaken?

**Comment by madhuris** [comment]
Hi Cory,

The heimdall related model imports have all been removed in the update. You should now be able to run orchestrator.py as shown in the Example Usage section.

Regards,
Madhuri
